import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await p.goto('http://localhost:4173/', { waitUntil: 'networkidle' }); await p.waitForTimeout(800);
await p.screenshot({ path: '/tmp/shots/m-hero.png' });
await p.evaluate(() => { const w = document.querySelector('.walk'); const top = w.getBoundingClientRect().top + window.scrollY; window.scrollTo({ top: top - 70 + 0.55 * (w.offsetHeight - window.innerHeight + 70) }); }); await p.waitForTimeout(1300);
await p.screenshot({ path: '/tmp/shots/m-walk.png' });
await p.evaluate(() => { const w = document.querySelector('.walk'); const top = w.getBoundingClientRect().top + window.scrollY; window.scrollTo({ top: top - 70 + 1.0 * (w.offsetHeight - window.innerHeight + 70) }); }); await p.waitForTimeout(1300);
await p.screenshot({ path: '/tmp/shots/m-walk-end.png' });
await b.close();
